name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.0
    - uses: actions/setup-dotnet@v1    
    - name: Run the dotnet test
      test: dotnet run    
    - name: Build with dotnet      
      run: dotnet build --configuration Release
